
package prog.vista;

import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import prog.modelo.Estadistica;

public class VistaEstadisticaJF extends javax.swing.JFrame {

    private final Estadistica estadistica;
    private final JTable tablaEstadisticas;
    
    /**
     * Creates new form VistaEstadisticaJF
     */
    public VistaEstadisticaJF() {
    // Crear una instancia de la clase Estadistica
    estadistica = new Estadistica();

    // Leer las estadísticas desde el archivo
    estadistica.leerEstadisticas();

    // Crear la tabla para mostrar las estadísticas
    tablaEstadisticas = new JTable();
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("Categoría");
    model.addColumn("Valor");
    
    // Agregar las filas a la tabla con los datos de la estadística
    model.addRow(new Object[]{"Ingresos a Aplicacion", estadistica.getIngresoGeneral()});
    model.addRow(new Object[]{"Ingresos a Menú Doctor", estadistica.getIngresoMenuDoctor()});
    model.addRow(new Object[]{"Ingresos a Menú Clientes", estadistica.getIngresoMenuClientes()});
    model.addRow(new Object[]{"Ingresos a Menú Mascotas", estadistica.getIngresoMenuMascotas()});
    model.addRow(new Object[]{"Ingresos a Menú Cursos", estadistica.getIngresoMenuCursos()});
    model.addRow(new Object[]{"Ingresos a Menú Remedios", estadistica.getIngresoMenuRemedios()});
    model.addRow(new Object[]{"Ingresos a Menú Consultas", estadistica.getIngresoMenuConsultas()});

    tablaEstadisticas.setModel(model);

    // Crear el panel y agregar la tabla dentro de un JScrollPane
    JPanel panel = new JPanel();
    JScrollPane scrollPane = new JScrollPane(tablaEstadisticas);
    panel.add(scrollPane);

    // Configurar el marco principal
    setTitle("Estadísticas");
    setSize(500, 400);
    setLocationRelativeTo(null); // Centrar el marco en la pantalla
    setContentPane(panel);
    setVisible(true);
    initComponents();
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Tabla de estadisticas de ingresos a menúes");
        setResizable(false);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Cerrar  Tabla");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(489, Short.MAX_VALUE)
                .addComponent(jButton2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose(); // Cerrar el JFrame
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
